WordTranslator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('translator.urls'))
]

translator/urls.py
from django.urls import path
from . import views

app_name = "translator"

urlpatterns = [
    path('', views.index, name='index'),
    path('mbiri/', views.about, name='about'),
]

translator/models.py
from django.db import models

# Create your models here.

translator/views.py
from django.shortcuts import render
from translator_data.eng_translator import evaluate, normalizeString

def index(request):
    if request.method == "POST":

        word = normalizeString(request.POST.get("word"))
       
        try:
            results = evaluate(word)
            result = ""
            for re in results:
                result += ' ' + re
        except KeyError:
            result = None

        if result is not None:
            data = {
                'word': word,
                'translation': str(result),
            }
            return render(request, 'index.html', data)
        else:
            result = "Pepani! Palibe matanthauzo omwe apezeka ku mawu omwe munalemba"
            data = {
                'word': word,
                'translation': result,
            }
            return render(request, 'index.html', data)
    else:
        return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')

templates/about.html
 {% extends 'base.html' %} {% load static %} {% block title %}
<title>Mtanthauzila mawu | Mbiri</title> {% endblock title %} {% block section_header %}
<section id="heroabout" class="d-flex align-items-center justify-content-center">
    <div class="container position-relative">
        <h1>Mbiri</h1>
    </div>
</section> {% endblock section_header %} {% block section_main %}
<!-- ======= About Section ======= -->
<section id="about" class="about">
    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <img src="{% static 'translator/img/chichewa_logo.png' %}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-6 pt-4 pt-lg-0">
                <h3>Mtanthauzila Mawu</h3>
                <p>
                    Iyi ndi njira ya makono yokuthandizani kutanthauzila mawu kuchoka ku chiyakhulo cha Chingerezi kupita ku Chichewa.
                </p>
                <p>
                    Cholinga chathu ndi kufuna kupitasa patsogolo ntchito yofuna kuthandiza mzika za dziko la Malawi kupeza ma uthenga ofunika pa nthito zawo komanso kutenga nawo gawo pa chitukuko cha dziko.
                </p>
                <p>Timakhulupira kuti ndikofunika kuti anthu azipeza mawuthenga muchilankhulo chomwe amalankhula.</p>
                
            </div>
        </div>
        <hr>
        <div style="text-align: center;">
            <div class="d-flex justify-content-center">
                <div class="mr-3">
                    <p>Developed by</p>
                    <img class="img-responsive" style="width: 110px; height: 110px" src="{% static 'translator/img/mustLogo.jfif' %}" alt="MUST">
                </div>
                <!-- <div style="border-right: 2px solid yellow;"></div> -->
                <div class="ml-3">
                    <p>Supported by</p>
                    <img class="img-responsive" src="{% static 'translator/img/unesco.png' %}" alt="MUST">
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock section_main %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"> {% block title %} {% endblock title %}
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link type="image/png" sizes="16x16" rel="icon" href="{% static 'translator/img/synchronize.png' %}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="{% static 'translator/css/style.css' %}" rel="stylesheet">
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-transparent">
        <div class="container d-flex align-items-center justify-content-between">

            <h1 class="logo"><a href="/">MM</a></h1>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link {% if request.path == '/'%} active {% endif %}" href="{% url 'translator:index' %}">Pofikira</a></li>
                    <li><a class="nav-link {% if request.path == '/mbiri/'%} active {% endif %}" href="{% url 'translator:about' %}">Mbiri</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- .navbar -->

        </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
    {% block section_header%} {% endblock section_header %}

    <!-- End Hero -->


    {% block section_main %} {% endblock section_main %}


    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="container py-2">

            <div class="me-md-auto text-center text-md-center py-2">
                <div class="copyright">
                    &copy; 2022 <strong><span>Mtanthauzira Mawu</span></strong>
                </div>
            </div>
           
        </div>
    </footer>
    <!-- End Footer -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'translator/js/main.js' %}"></script>

    {% block js_script %} {% endblock js_script %}

</body>

</html>

templates/index.html
{% extends 'base.html' %}{% load static %} {% block title %}
<title>Mtanthauzira Mawu | Pofikila</title> {% endblock title %} {% block section_header %}
<section id="heroabout" class="d-flex align-items-center justify-content-center">
    <div class="container position-relative">
        <h1>Mtanthauzira Mawu</h1>
        <h2>Iyi ndi njira yodalirika potanthauzira mawu kuchoka ku Chingerezi kupita ku Chichewa</h2>
    </div>
</section> {% endblock section_header %} {% block section_main %}
<section id="tranz" class="d-flex justify-content-center">
    <div class="container position-relative">
        <form method="POST">
            {% csrf_token %}
        
                <div class="text-center">
                    <div class="form">
                        <textarea name="word" id="word" cols="10" rows="5" class="form-control" placeholder="Lembani mawu anu apa" required>{% if word %} {{ word }} {% endif %}</textarea>
                    </div>
                </div>
                
            <button class="btn-translate btn" style="text-align: center;">Tanthauzirani</button>
        </form>

        <div class="row mt-3">
            {% if translation %}
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card card-result">
                    <div class="card-body">
                        <h5 class="card-title">Tanthauzo</h5>
                        <hr>
                        <p class="card-text">{% if translation %} {{ translation }} {% endif %}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-2">

            </div>
            <a href="{% url 'translator:index' %}">Yambiraninso</a> {% endif %}
        </div>
    </div>
</section>{% endblock section_main %}